FROM icr.io/appcafe/open-liberty:full-java11-openj9-ubi

COPY --chown=1001:0 target/liberty/wlp/usr/servers/defaultServer/bootstrap.properties /config
COPY --chown=1001:0 target/liberty/wlp/usr/servers/defaultServer/server.xml /config

#RUN features.sh

COPY --chown=1001:0 target/*.war /config/apps

RUN configure.sh

